well_commerce_currency:
    configuration:
        currency:
            orm:
                factory: WellCommerce\Bundle\CurrencyBundle\Factory\CurrencyFactory
                repository: WellCommerce\Bundle\CurrencyBundle\Repository\CurrencyRepository
                mapping: "@WellCommerceCurrencyBundle/Resources/config/doctrine/Currency.orm.yml"
                entity: WellCommerce\Bundle\CurrencyBundle\Entity\Currency
            api:
                exposed: true
                dataset: currency.dataset.admin
                manager: currency.manager.admin
        currency_rate:
            orm:
                factory: WellCommerce\Bundle\CurrencyBundle\Factory\CurrencyRateFactory
                repository: WellCommerce\Bundle\CurrencyBundle\Repository\CurrencyRateRepository
                mapping: "@WellCommerceCurrencyBundle/Resources/config/doctrine/CurrencyRate.orm.yml"
                entity: WellCommerce\Bundle\CurrencyBundle\Entity\CurrencyRate
