WellCommerce\Bundle\CurrencyBundle\Entity\CurrencyRate:
    fields:
        id:
            groups:
                - default
                - currency_rate
        currencyFrom:
            groups:
                - default
                - currency_rate
        currencyTo:
            groups:
                - default
                - currency_rate
        exchangeRate:
            groups:
                - default
                - currency_rate
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        createdBy:
            groups:
                - currency_rate
        updatedBy:
            groups:
                - currency_rate
        deletedBy:
            groups:
                - currency_rate
    callbacks: {  }
