# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_api:
    request_handler:
        currency:
            manager: currency.manager
    serialization:
        WellCommerce\Bundle\CurrencyBundle\Entity\Currency:
            mapping: "@WellCommerceCurrencyBundle/Resources/config/serialization/Currency.yml"
        WellCommerce\Bundle\CurrencyBundle\Entity\CurrencyRate:
            mapping: "@WellCommerceCurrencyBundle/Resources/config/serialization/CurrencyRate.yml"
